= DispatcherServlet
:listing-caption!:

스프링 MVC는 프론트 컨트롤러 패턴으로 구현되어 있으며, 여기서 프론트 컨트롤러 역할을 하는 것이 `DispatcherSevlet` 이며, 스프링 MVC의 핵심이라고 할 수 있다. `DispatcherServlet` 도 부모 클래스에서 `HttpServlet` 클래스를 상속받아 서블릿으로 동작한다.

서블릿이 호출되면 `HttpServlet` 의 `service()` 메소드가 호출되게 된다. 스프링 MVC는 `DispatcherServlet` 의 부모인 `FrameworkServlet` 에서 `servie()` 메소드를 구현해두었고, 이 부분을 시작으로 `DispatcherServlet` 의 `doDispatch()` 메소드가 시작된다.

첫 번째로, `@RequestMapping` 어노테이션이 붙은 컨트롤러(핸들러)에 해당하는 요청이 들어왔을 경우를 확인해보자.

.HelloController.jaa
[,java]
----
@Controller
public class HelloController {
    @Autowired
    HelloService helloService;

    @GetMapping("/first")
    @ResponseBody
    public String first() {
        return "Hello, Stranger.";
    }
}
----

.DispatcherServlet.java
[#DispatcherServlet,java]
----
protected void doDispatch(HttpServletRequest request, HttpServletResponse response) throws Exception {
    HttpServletRequest processedRequest = request;
    HandlerExecutionChain mappedHandler = null;
    boolean multipartRequestParsed = false;
    WebAsyncManager asyncManager = WebAsyncUtils.getAsyncManager(request);

    try {
        try {
            ModelAndView mv = null;
            Exception dispatchException = null;

            try {
                processedRequest = this.checkMultipart(request);
                multipartRequestParsed = processedRequest != request;
                mappedHandler = this.getHandler(processedRequest); <.>
                ...
}

protected HandlerExecutionChain getHandler(HttpServletRequest request) throws Exception {
    // 1. org.springframework.web.servlet.handler.BeanNameUrlHandlerMapping
    //    스프링 빈의 이름으로 핸들러를 찾는다.
    // 2. org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping
    //    어노테이션 기반의 컨트롤러인, @RequestMapping이 붙은 핸들러를 찾는다.
    // 3. org.springframework.web.servlet.function.support.RouterFunctionMapping
    if (this.handlerMappings != null) {
        Iterator var2 = this.handlerMappings.iterator();

        while(var2.hasNext()) {
            HandlerMapping mapping = (HandlerMapping)var2.next();
            HandlerExecutionChain handler = mapping.getHandler(request); <.>
            if (handler != null) {
                return handler;
            }
        }
    }
    return null;
}

protected void doDispatch(HttpServletRequest request, HttpServletResponse response) throws Exception {
                ...
                if (mappedHandler == null) {
                    this.noHandlerFound(processedRequest, response);
                    return;
                }

                HandlerAdapter ha = this.getHandlerAdapter(mappedHandler.getHandler()); <.>
                ...
}

protected HandlerAdapter getHandlerAdapter(Object handler) throws ServletException {
    // 1. org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter
    // 2. org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter
    // 3. org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter
    // 4. org.springframework.web.servlet.function.support.HandlerFunctionAdapter
    if (this.handlerAdapters != null) {
        Iterator var2 = this.handlerAdapters.iterator();

        while(var2.hasNext()) {
            HandlerAdapter adapter = (HandlerAdapter)var2.next();
            if (adapter.supports(handler)) {
                return adapter; <.>
            }
        }
    }

    throw new ServletException("No adapter for handler [" + handler + "]: The DispatcherServlet configuration needs to include a HandlerAdapter that supports this handler");
}

protected void doDispatch(HttpServletRequest request, HttpServletResponse response) throws Exception {
                ...
                String method = request.getMethod();
                boolean isGet = HttpMethod.GET.matches(method);
                if (isGet || HttpMethod.HEAD.matches(method)) {
                    long lastModified = ha.getLastModified(request, mappedHandler.getHandler());
                    if ((new ServletWebRequest(request, response)).checkNotModified(lastModified) && isGet) {
                        return;
                    }
                }

                if (!mappedHandler.applyPreHandle(processedRequest, response)) {
                    return;
                }

                mv = ha.handle(processedRequest, response, mappedHandler.getHandler()); <.>
                ...
}
----
<.> 해당 요청을 처리할 수 있는 핸들러를 찾아오는 메소드를 호출한다.
<.> 등록 되어있는 `HandlerMapping` 을 차례로 돌면서 해당 요청을 처리할 수 있는 핸들러를 찾아서 반환한다.
<.> 해당 핸들러를 실행할 수 있는 핸들러 어댑터를 찾아오는 메소드를 호출한다.
<.> 등록 되어있는 `HandlerAdapter` 를 차례로 돌면서 해당 핸들러를 실행시킬 수 있는 핸들러 어댑터를 찾아서 반환한다.
<.> 찾아온 핸들러 어댑터에서 실제 요청을 처리하는 메소드를 호출한다.

.RequestMappingHandlerAdapter.java
[,java]
----
@Nullable
    protected ModelAndView invokeHandlerMethod(HttpServletRequest request, HttpServletResponse response, HandlerMethod handlerMethod) throws Exception {
    ServletWebRequest webRequest = new ServletWebRequest(request, response);

    Object result;
    try {
        WebDataBinderFactory binderFactory = this.getDataBinderFactory(handlerMethod);
        ModelFactory modelFactory = this.getModelFactory(handlerMethod, binderFactory);
        ServletInvocableHandlerMethod invocableMethod = this.createInvocableHandlerMethod(handlerMethod);
        if (this.argumentResolvers != null) {
            invocableMethod.setHandlerMethodArgumentResolvers(this.argumentResolvers);
        }

        if (this.returnValueHandlers != null) {
            invocableMethod.setHandlerMethodReturnValueHandlers(this.returnValueHandlers);
        }
        ...
        invocableMethod.invokeAndHandle(webRequest, mavContainer, new Object[0]); <.>
        if (!asyncManager.isConcurrentHandlingStarted()) {
            ModelAndView var15 = this.getModelAndView(mavContainer, modelFactory, webRequest);
            return var15;
        }

        result = null;
    } finally {
        webRequest.requestCompleted();
    }

    return (ModelAndView)result;
}
----
<.> 해당 요청을 실행하는 메소드를 호출한다.

.ServletInvocableHandlerMethod.java
[,java]
----
public void invokeAndHandle(ServletWebRequest webRequest, ModelAndViewContainer mavContainer, Object... providedArgs) throws Exception {
    Object returnValue = this.invokeForRequest(webRequest, mavContainer, providedArgs); <.>
    ...
}
----
<.> 핸들러를 호출한다. 리플렉션을 사용하여 해당 메소드를 invoke 시킨다.

.HelloController.java
[,java]
----
@GetMapping("/first")
public String hello() {
    return "Hello, Stranger";
}
----

.ServletInvocableHandlerMethod.java
[,java]
----
public void invokeAndHandle(ServletWebRequest webRequest, ModelAndViewContainer mavContainer, Object... providedArgs) throws Exception {
    ...
    this.setResponseStatus(webRequest);
    if (returnValue == null) { <.>
        if (this.isRequestNotModified(webRequest) || this.getResponseStatus() != null || mavContainer.isRequestHandled()) {
            this.disableContentCachingIfNecessary(webRequest);
            mavContainer.setRequestHandled(true);
            return;
        }
    } else if (StringUtils.hasText(this.getResponseStatusReason())) {
        mavContainer.setRequestHandled(true);
        return;
    }

    mavContainer.setRequestHandled(false);
    Assert.state(this.returnValueHandlers != null, "No return value handlers");

    try {
        this.returnValueHandlers.handleReturnValue(returnValue, this.getReturnValueType(returnValue), mavContainer, webRequest); <.>
    } catch (Exception var6) {
        if (logger.isTraceEnabled()) {
            logger.trace(this.formatErrorForReturnValue(returnValue), var6);
        }

        throw var6;
    }
}
----
<.> `@RestController` 일 경우에, `returnValue` 는 문자열이 된다.
<.> `returnValue` 를 처리할 수 있는 핸들러를 찾아서 실행시키기 위해 `returnValueHandlers` 의 메소드를 호출한다.

.HandlerMethodReturnValueHandlerComposite.java
[,java]
----
public class HandlerMethodReturnValueHandlerComposite implements HandlerMethodReturnValueHandler {
    // .. RequestResponseBodyMethodProcessor
    private final List<HandlerMethodReturnValueHandler> returnValueHandlers = new ArrayList();
    ...
    public void handleReturnValue(@Nullable Object returnValue, MethodParameter returnType, ModelAndViewContainer mavContainer, NativeWebRequest webRequest) throws Exception {
        HandlerMethodReturnValueHandler handler = this.selectHandler(returnValue, returnType); <.>
        ...
    }
    private HandlerMethodReturnValueHandler selectHandler(@Nullable Object value, MethodParameter returnType) {
        boolean isAsyncValue = this.isAsyncReturnValue(value, returnType);
        Iterator var4 = this.returnValueHandlers.iterator();

        HandlerMethodReturnValueHandler handler;
        do {
            do {
                if (!var4.hasNext()) {
                    return null;
                }

                handler = (HandlerMethodReturnValueHandler)var4.next();
            } while(isAsyncValue && !(handler instanceof AsyncHandlerMethodReturnValueHandler));
        } while(!handler.supportsReturnType(returnType)); <.>

        return handler;
    }
    ...
    public void handleReturnValue(@Nullable Object returnValue, MethodParameter returnType, ModelAndViewContainer mavContainer, NativeWebRequest webRequest) throws Exception {
        ...
        if (handler == null) {
            throw new IllegalArgumentException("Unknown return value type: " + returnType.getParameterType().getName());
        } else {
            handler.handleReturnValue(returnValue, returnType, mavContainer, webRequest); <.>
        }
    }
----
<.> `returnType` 을 처리할 수 있는 핸들러를 찾는 메소드를 호출한다.
<.> `HandlerMethodReturnValueHandler` 의 구현체들이 구현하고 있는 `supportsReturnType` 메소드를 호출해서, `returnType` 을 지원하는 핸들러인지 확인한다.
<.> 위에서 찾은 응답 핸들러를 실행해서 `returnValue` 를 처리한다.

.RequestResponseBodyMethodProcessor.java
[,java]
----
public boolean supportsReturnType(MethodParameter returnType) { <.>
    return AnnotatedElementUtils.hasAnnotation(returnType.getContainingClass(), ResponseBody.class) || returnType.hasMethodAnnotation(ResponseBody.class);
}
----
<.> `RequestResponseBodyMethodProcessor` 응답 핸들러는 클래스 또는 메소드에 `@ResponseBody` 어노테이션이 붙어있는 `returnType` 을 처리할 수 있다.


지금처럼 `@ResponseBody` 가 붙은 핸들러에 해당하는 요청을 처리하는 경우에는, xref:DispatcherServlet[DispatcherServlet] 에서 핸들러 어댑터를 통해 요청을 처리한 뒤의 반환 값인 `mv` 는 `null` 이 된다. `@ResponseBody` 가 붙지 않았지만 `returnType` 이 문자열인 경우에는

.HelloController.java
[,java]
----
@Controller
public class HelloController {
    @GetMapping("/first")
    @ResponseBody
    public String hello() {
        return "Hello, Stranger.";
    }

    @GetMapping("/second")
    public String second() {
        return "/WEB-INF/second.jsp";
    }
}
----

.ViewNameMethodReturnValueHandler.java
[,java]
----
public class ViewNameMethodReturnValueHandler implements HandlerMethodReturnValueHandler {

    public boolean supportsReturnType(MethodParameter returnType) {
        Class<?> paramType = returnType.getParameterType();
        return Void.TYPE == paramType || CharSequence.class.isAssignableFrom(paramType);
    }

    public void handleReturnValue(@Nullable Object returnValue, MethodParameter returnType, ModelAndViewContainer mavContainer, NativeWebRequest webRequest) throws Exception {
        if (returnValue instanceof CharSequence) { <.>
            String viewName = returnValue.toString();
            mavContainer.setViewName(viewName);
            if (this.isRedirectViewName(viewName)) {
                mavContainer.setRedirectModelScenario(true);
            }
        } else if (returnValue != null) {
            throw new UnsupportedOperationException("Unexpected return type: " + returnType.getParameterType().getName() + " in method: " + returnType.getMethod());
        }

    }
}
----
<.> `returnValue` 를 `viewName` 으로 판단하여 `ModelAndViewContainer` 객체에 값을 세팅한다.

.RequestMappingHandlerAdapter.java
[,java]
----
@Nullable
    protected ModelAndView invokeHandlerMethod(HttpServletRequest request, HttpServletResponse response, HandlerMethod handlerMethod) throws Exception {
        ...
        invocableMethod.invokeAndHandle(webRequest, mavContainer, new Object[0]);
        if (!asyncManager.isConcurrentHandlingStarted()) {
            ModelAndView var15 = this.getModelAndView(mavContainer, modelFactory, webRequest); <.>
            return var15;
        }

        result = null;
    } finally {
        webRequest.requestCompleted();
    }

    return (ModelAndView)result;
}
----
<.> 핸들러에서 `ModelAndViewContainer` 객체에 값을 세팅한 것을 가지고 `ModelAndView` 객체를 생성해서 리턴한다.

두 번째로, `Controller` 인터페이스를 구현한 컨트롤러(핸들러)에 해당하는 요청이 들어왔을 경우를 확인해보자. 이 경우에 사용되는 핸들러 매핑은 `BeanNameUrlHandlerMapping` 이고, 이 핸들러를 실행시킬 수 있는 핸들러 어댑터는 `SimpleControllerHanlderAdapter` 가 된다.

.SimpleController.java
[,java]
----
@Controller("/simple")
public class SimpleController implements org.springframework.web.servlet.mvc.Controller {
    @Override
    public ModelAndView handleRequest(HttpServletRequest request, HttpServletResponse response) throws Exception {
        return new ModelAndView("/WEB-INF/simple.jsp");
    }
}
----

== 정리
=== DispatcherServlet 동작 순서
1. 요청을 분석한다. (로케일, 테마, 멀티파트 등)
2. (핸들러 맵핑에게 위임하여) 요청을 처리할 핸들러를 찾는다.
3. (등록되어 있는 핸들러 어댑터 중에) 해당 핸들러를 실행할 수 있는 핸들러 어댑터를 찾는다.
4. 찾아낸 핸들러 어댑터를 사용해서 핸들러의 응답을 처리한다.
* 핸들러의 리턴값을 보고 어떻게 처리할지 판단한다.
* 뷰 이름에 해당하는 뷰를 찾아서 모델 데이터를 랜더링한다.
* `@ResponseBody` 가 있다면 Converter를 사용해서 응답 본문을 만들고.
5. (부가적으로) 예외가 발생했다면, 예외 처리 핸들러에 요청 처리를 위임한다.
6. 최종적으로 응답을 보낸다.


.DispatcherServlet.java
[,java]
----
protected void initStrategies(ApplicationContext context) { <.>
    this.initMultipartResolver(context);
    this.initLocaleResolver(context);
    this.initThemeResolver(context);
    this.initHandlerMappings(context);
    this.initHandlerAdapters(context);
    this.initHandlerExceptionResolvers(context);
    this.initRequestToViewNameTranslator(context);
    this.initViewResolvers(context);
    this.initFlashMapManager(context);
}
private void initViewResolvers(ApplicationContext context) {
    this.viewResolvers = null;
    if (this.detectAllViewResolvers) {
        Map<String, ViewResolver> matchingBeans = BeanFactoryUtils.beansOfTypeIncludingAncestors(context, ViewResolver.class, true, false); <.>
        if (!matchingBeans.isEmpty()) {
            this.viewResolvers = new ArrayList(matchingBeans.values());
            AnnotationAwareOrderComparator.sort(this.viewResolvers);
        }
    } else { <.>
        try {
            ViewResolver vr = (ViewResolver)context.getBean("viewResolver", ViewResolver.class);
            this.viewResolvers = Collections.singletonList(vr);
        } catch (NoSuchBeanDefinitionException var3) {
        }
    }

    if (this.viewResolvers == null) {
        this.viewResolvers = this.getDefaultStrategies(context, ViewResolver.class); <.>
        if (this.logger.isTraceEnabled()) {
            this.logger.trace("No ViewResolvers declared for servlet '" + this.getServletName() + "': using default strategies from DispatcherServlet.properties");
        }
    }
}
----
<.> 서블릿이 초기화 `init()` 될 때 한 번만 호출된다.
<.> `ViewResolver` 타입의 빈들을 찾아와서 `viewResolvers` 리스트에 넣어둔다.
<.> 기본적으로 `detectAllViewResolvers` 는 `true` 값을 갖지만, `false` 인 경우 빈 이름이 정확하게 `viewResolver` 이면서 `ViewResolver` 타입의 빈을 하나만 가져와서 넣는다. 일반적으로 `detectAllViewResolver` 는 기본 값을 사용한다.
<.> 이 때, 등록된 `ViewResolvers` 타입의 빈들이 없다면 `DispatcherServlet.properties` 에 정의된 기본 전략을 사용한다.

.DispatcherServlet.properties
[,]
----
org.springframework.web.servlet.ViewResolver=org.springframework.web.servlet.view.InternalResourceViewResolver
----
