= Servlet
:listing-caption!:

== Java EE와 서블릿
Java EE::
자바의 기본적인 기능들을 정의한 Java SE에 웹 어플리케이션을 위한 스펙을 추가한 표준을 말한다.
서블릿::
서블릿은 Java EE 스펙 중 하나로, 자바를 사용하여 웹페이지를 동적으로 생성하는 서버측 프로그램 혹은 그 사양을 말한다.
WAS::
Java EE 스펙을 구현한 제품을 웹 어플리케이션 서버(WAS)라고 한다.
서블릿 컨테이너::
서블릿을 지원하는 WAS를 서블릿 컨테이너라고 한다. 톰캣, 제티, 언더토 등이 있으며, 서블릿 어플리케이션을 실행하기 위해서는 반드시 서블릿 컨테이너가 필요하다.
* HTTP 요청과 응답에 필요한 공통 로직들을 서블릿 컨테이너에서 처리해주기 때문에 개발자는 HTTP 스펙을 편리하게 사용할 수 있다.
* 서블릿의 생성, 초기화, 호출, 종료 등의 생명 주기를 관리한다.
* 서블릿 객체를 싱글톤으로 관리하며, 서블릿 컨테이너가 종료될 때 함께 종료 된다.
* 멀티 쓰레드를 지원하여 관련된 부분을 처리해준다.
** 쓰레드가 필요하면, 이미 생성되어 있는 쓰레드를 쓰레드 풀에서 꺼내서 사용한다. 사용을 종료하면 쓰레드 풀에 해당 쓰레드를 반납한다.
** 멀티 쓰레드와 관련된 부분을 WAS가 처리하기 때문에, 개발자는 마치 싱글 쓰레드 프로그래밍을 하는 것처럼 편리하게 개발할 수 있다.
** 다만 멀티 쓰레드 환경이므로 싱글톤 객체는 주의해서 사용해야한다.

=== 서블릿 컨테이너의 동작 방식
. 요청이 오면, 서블릿 컨테이너는 요청 정보에 따라 서블릿 객체를 찾는다. 이 때,
해당 서블릿 객체가 생성되지 않았으면(최초 요청) `init()` 메소드를 호출하여 메모리에 올린 뒤 객체를 생성하여 초기화한다. 최초 요청 이후부터는 호출되지 않는다.
. 초기화된 후에는 실제 서블릿에서 처리해야 하는 내용이 구현되어 있는 `service()` 메소드를 호출한다. HTTP 메소드에 따라 `doGet()`, `doPost()` 을 오버라이딩하여 처리를 위임하게 할 수도 있다.
.. WAS는 요청이 오면 `service()` 메소드를 호출하기 전에 `HttpServletRequest`, `HttpServletResponse` 객체를 생성하여 서블릿 객체를 호출해준다. 개발자는 여기에서 필요한 정보를 꺼내서 HTTP 정보들을 편리하게 사용할 수 있다.
. 서블릿 컨테이너 판단에 따라 해당 서블릿을 메모리에서 내려야 할 시점(WAS가 종료될 때 등)에 destroy()를
호출한다.


== 서블릿 생성과 등록
* 프로젝트 생성 (Intelij)
** File > New > Project > Maven Archetypes
*** org.apache.maven.archetypes:maven-archetype-webapp

.pom.xml
[,xml]
----
<dependency>
    <groupId>javax.servlet</groupId>
    <artifactId>javax.servlet-api</artifactId>
    <version>4.0.1</version>
    <scope>provided</scope> #<.>
</dependency>
----
<.> 런타임 시점에 외부(톰캣)에서 제공될 것이기 때문에 런타임에는 해당 의존성이 클래스패스에서 빠진다.

.HelloServlet.java
[, java]
----
package hello;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

public class HelloServlet extends HttpServlet { //<.>
    @Override
    public void init() throws ServletException {
        System.out.println("HelloServlet.init"); // <.>
    }

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        System.out.println("HelloServlet.doGet"); // <.>
        resp.getWriter().println("<html>");
        resp.getWriter().println("<head>");
        resp.getWriter().println("<body>");
        resp.getWriter().println("<h1>Hello Servlet</h1>");
        resp.getWriter().println("</body>");
        resp.getWriter().println("</head>");
        resp.getWriter().println("</html>");
        resp.getWriter().println("</html>");
    }

    @Override
    public void destroy() {
        System.out.println("HelloServlet.destroy"); // <.>
    }
}
----
<.> 서블릿을 구현할 때 상속 받아야 하는 클래스
<.> 해당 서블릿이 최초로 요청을 받았을 때 실행된다.
<.> 해당 서블릿에 대한 요청이 있을 때마다 실행된다.
<.> 해당 서블릿이 메모리에서 해제될 때 실행된다.

.web.xml
[,xml]
----
<web-app> #<.>
  <servlet> #<.>
    <servlet-name>hello</servlet-name>
    <servlet-class>hello.HelloServlet</servlet-class>
  </servlet>
  <servlet-mapping> #<.>
    <servlet-name>hello</servlet-name>
    <url-pattern>/hello</url-pattern>
  </servlet-mapping>
 </web-app>
----
<.> web.xml은 웹 애플리케이션 실행에 관해 설정하는 환경설정 파일이며, 웹 어플리케이션 서비스 시작 시 웹 서버가 읽어서 사용한다.
<.> 서블릿을 web.xml에 등록할 때 사용한다.
<.> <servlet>에서 등록한 서블릿 정보로 URL과 매핑한다.


[TIP]
====
서블릿 3.0 버전(톰캣 7 이상) 부터는 `@WebServlet` 어노테이션을 지원하는데, web.xml에 등록하는 대신에 이 어노테이션으로 서블릿을 등록하고 URL 매핑을 할 수 있다.

.HelloServlet.java
[,java]
----
@WebServlet(name = "helloServlet", urlPatterns = "/hello")
public class HelloServlet extends HttpServlet {}
----
====

다음 URL로 호출해보자.

    http://localhost:8080/hello

    HelloServlet.init
    HelloServlet.doGet
    request = org.apache.catalina.connector.RequestFacade@11d0a084
    response = org.apache.catalina.connector.ResponseFacade@15ef2666

`RequestFacade`, `ResponseFacade` 는 톰캣에서 `HttpServletRequest`, `HttpServletResponse` 를 구현한 객체이다.

== 서블릿 리스너와 필터
=== 서블릿 필터
서블릿이 수행되기 전 또는 후에  특별한 처리가 필요한 경우에 사용할 수 있다.

.MyFilter.java
[,java]
----
package hello;

import javax.servlet.*;
import java.io.IOException;

public class MyFilter implements Filter { //<.>
    @Override
    public void init(FilterConfig filterConfig) throws ServletException { //<.>
        System.out.println("MyFilter.init");
    }

    @Override
    public void doFilter(ServletRequest servletRequest, ServletResponse servletResponse, FilterChain filterChain) throws IOException, ServletException {
        System.out.println("MyFilter.doFilter before");
        filterChain.doFilter(servletRequest, servletResponse); //<.>
        System.out.println("MyFilter.doFilter after");
    }

    @Override
    public void destroy() { //<.>
        System.out.println("MyFilter.destroy");
    }
}

----
<.> 필터를 구현할 때는 `javax.servlet.Filter` 인터페이스를 상속 받아야 한다.
<.> 톰캣이 시작될 때 한 번만 호출된다.
<.> `doFilter` 메소드를 사용해서 다음 필터로 연결 해주지 않으면 여기서 바로 클라이언트에 응답하게 된다. 마지막 필터인 경우, 서블릿으로 연결된다. `doFilter` 전의 로직은 서블릿 호출 전에, `doFilter` 후의 로직은 서블릿 호출된 후에 실행된다.
<.> 톰캣이 종료될 때(필터 객체가 메모리에서 삭제될 때) 한 번만 호출된다.

.web.xml
[,xml]
----
<filter>
    <filter-name>myFilter</filter-name>
    <filter-class>hello.MyFilter</filter-class>
</filter>
<filter-mapping>
    <filter-name>myFilter</filter-name>
    <servlet-name>hello</servlet-name> #<.>
</filter-mapping>
----
<.> 해당 서블릿이 호출될 때 필터가 실행된다. `<url-pattern>` 태그를 사용해서 URL과 매핑할 수도 있다.

[CAUTION]
====
web.xml에는 특정한 규칙들이 있는데, 순서 대로 나열하지 않으면 에러가 발생하기도 한다.

    The content of element type "web-app" must match
    "(icon?,display-name?,description?,distributable?,context-param*,filter*,
    filter-mapping*,listener*,servlet*,servlet-mapping*,session-config?,
    mime-mapping*,welcome-file-list?,error-page*,taglib*,resource-env-ref*,
    resource-ref*,security-constraint*,login-config?,security-role*,env-entry*,
    ejb-ref*,ejb-local-ref*)".
====
[TIP]
====
`@WebFilter` 어노테이션을 사용해서 필터를 등록할 수 있다.

.MyFilter.java
[,java]
----
@WebFilter(filterName = "myFilter", servletNames = "hello")
public class MyFilter implements Filter {}
----
====

톰캣을 구동한 뒤에 서블릿을 호출해보면 다음과 같다.
[]
----
MyFilter.init <.>

HelloServlet.init <.>
MyFilter.doFilter before
HelloServlet.doGet
MyFilter.doFilter after

MyFilter.destroy <.>
----
<.> 톰캣을 실행했을 때 필터가 초기화 된다.
<.> `hello` 서블릿이 호출되었을 때 최초 초기화가 발생하고, 필터가 실행된 후 서블릿이 호출된다. 그 이후에 다시 필터로 돌아와 남은 로직이 수행된다.
<.> 톰캣이 종료되었을 때 메모리에서 필터 객체가 삭제되고, `destroy()` 메소드가 호출된다.


=== 서블릿 리스너
이벤트 핸들러라고도 하며, 서블릿 API에서는 `ServletContext`, `HttpSession`, `HttpServletRequest` 세 개의 객체에서 이벤트가 발생할 경우 자동으로 호출될 메소드들을 가지고 있는 리스너를 제공한다.

그 중에서 `ServletContext` 객체가 생성되거나 해제될 때 발생하는 이벤트를 핸들링하기 위한 리스너 인터페이스인 `ServletContextListener` 를 사용해서 리스너를 등록해보자.

[TIP]
https://www.javatpoint.com/Event-and-Listener-in-Servlet[서블릿 리스너에 대한 더 자세한 사항은 해당 링크를 참고]

[TIP]
====
ServletContext::
* 서블릿 컨테이너는 WAS에 등록된 웹 어플리케이션 단위로 `Context` 를 생성하여 관리하는데, 이것이 `ServletContext` 이다. 웹 어플리케이션과 생명 주기를 함께 하며, 동일한 웹 애플리케이션에 존재하는 서블릿들은 동일한 `ServletContext` 객체를 사용하게 된다.
* `ServletContext` 객체가 가지고 있는 변수는 동일한 웹 어플리케이션에 속한 모든 페이지에서 사용할 수 있는 전역 변수이다. `web.xml` 파일에 `<context-param>` 을 사용해서 ServletContext` 가 생성될 때 변수를 설정할 수 있다.

[source,xml]
----
<context-param>
    <param-name>contextConfig</param-name>
    <param-value>/WEB-INF/context.xml</param-value>
</context-param>
----
====

.MyListener.java
[,java]
----
package hello;

import javax.servlet.ServletContextEvent;
import javax.servlet.ServletContextListener;

public class MyListener implements ServletContextListener {
    @Override
    public void contextInitialized(ServletContextEvent sce) { //<.>
        System.out.println("MyListener.contextInitialized");
        sce.getServletContext().setAttribute("name", "jee");
    }

    @Override
    public void contextDestroyed(ServletContextEvent sce) { //<.>
        System.out.println("MyListener.contextDestroyed");
    }
}

----
<.> `ServletContext` 객체가 생성될 때 호출된다.
<.> `ServletContext` 객체가 삭제될 때 호출된다.

.web.xml
[,xml]
----
<listener>
    <listener-class>hello.MyListener</listener-class>
</listener>
----
[TIP]
====
`@WebListener` 어노테이션을 사용해서도 리스너를 등록할 수 있다.

.MyListener.java
[,java]
----
@WebListener
public class MyListener implements ServletContextListener {}
----
====

톰캣을 구동한 뒤에 서블릿을 호출해보면 다음과 같다.
[]
----
MyListener.contextInitialized <.>

HelloServlet.init
HelloServlet.doGet

MyListener.contextDestroyed <.>
----
<.> 톰캣을 실행하고 `ServletContext` 객체가 생성되면, `ServletContextListener` 인터페이스 구현체의 `contextInitialized()` 메소드가 호출된다.
<.> 톰캣이 종료되고 `ServletContext` 객체가 삭제되면, `ServletContextListener` 인터페이스 구현체의 `contextDestroyed()` 메소드가 호출된다.

== 스프링 IoC 컨테이너 연동하기
=== ContextLoaderListener
* `ContextLoaderListener` 는 `ServletContextListener` 를 상속받는 리스너이다.
* 그렇기 때문에, `ContextLoaderListener` 는 `ServletConext` 의 라이프 사이클에 맞춰서, 스프링 IoC 컨테이너인 `ApplicationContext` 를 `ServletContext` 에 등록해줄 수 있다.


[,java]
----
public class ContextLoaderListener extends ContextLoader implements ServletContextListener {
    public ContextLoaderListener() {
    }

    public ContextLoaderListener(WebApplicationContext context) {
        super(context);
    }

    public void contextInitialized(ServletContextEvent event) {
        this.initWebApplicationContext(event.getServletContext()); <.>
    }

    public void contextDestroyed(ServletContextEvent event) {
        this.closeWebApplicationContext(event.getServletContext());
        ContextCleanupListener.cleanupAttributes(event.getServletContext());
    }
}
----
<.> `ServletContext` 가 생성될 때 트리거되어 `WebApplicationContxt` 를 생성해주는 메소드를 호출하게 된다.

[,java]
----
public class ContextLoader {
    public WebApplicationContext initWebApplicationContext(ServletContext servletContext) {
            ...
            try {
                if (this.context == null) {
                    this.context = this.createWebApplicationContext(servletContext);
                }
                ...
                servletContext.setAttribute(WebApplicationContext.ROOT_WEB_APPLICATION_CONTEXT_ATTRIBUTE, this.context); <.>
                ...

public interface WebApplicationContext extends ApplicationContext {
    String ROOT_WEB_APPLICATION_CONTEXT_ATTRIBUTE = WebApplicationContext.class.getName() + ".ROOT";
    ...
}
----
<.> 생성된 `ApplicationContext` 를 `servletContext` 의 attribute에 저장해주고 있다.


[%hardbreaks]

=== ApplicationContext의 생성

* `ContextLoaderListener` 는 `contextClass` 와 `contextConfigLocation` 을 참고해서 `WebApplicationContext` 를 생성한다.
** `ApplicationContext` 를 만들어야 한다 ➔ 스프링 설정 파일이 있어야 한다
* `AnnotationConfigWebApplicationContext` 는 `(Web)ApplicationContext` 의 구현체로, 어노테이션 기반의 자바 설정 파일을 사용해 `ApplicationContext` 를 생성할 수 있다.
** `AppConfig.java`

.pom.xml
[,xml]
----
<dependency> <.>
  <groupId>org.springframework</groupId>
  <artifactId>spring-webmvc</artifactId>
  <version>5.3.21</version>
</dependency>
----
<.> 스프링 MVC 의존성 추가

.web.xml
[,xml]
----
<context-param> <.>
    <param-name>contextClass</param-name>
    <param-value>org.springframework.web.context.support.AnnotationConfigWebApplicationContext</param-value>
</context-param>
<context-param>
    <param-name>contextConfigLocation</param-name>
    <param-value>hello.AppConfig</param-value>
</context-param>
<listener>
  <listener-class>org.springframework.web.context.ContextLoaderListener</listener-class>
</listener>
----
<.> ServletContext 객체가 생성될 때 넘겨줄 파라미터를 설정할 수 있다.

.AppConfig.java
[,java]
----
package hello;
@Configurable
@ComponentScan(excludeFilters = @ComponentScan.Filter(Controller.class))
public class AppConfig {
}
----

.HelloService.java
[,java]
----
package hello;
@Service
public class HelloService {
    public String getName() {
        return "elliot";
    }
}
----

[,java]
----
package hello;

@WebServlet(name = "hello", urlPatterns = "/hello")
public class HelloServlet extends HttpServlet {
    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        ApplicationContext context = (ApplicationContext) getServletContext().getAttribute(WebApplicationContext.ROOT_WEB_APPLICATION_CONTEXT_ATTRIBUTE); <.>
        HelloService helloService = context.getBean(HelloService.class); <.>

        System.out.println("HelloServlet.doGet");
        resp.getWriter().println("<html>");
        resp.getWriter().println("<head>");
        resp.getWriter().println("<body>");
        resp.getWriter().println("<h1>Hello Servlet " + getServletContext().getAttribute("name") + "</h1>");
        resp.getWriter().println("<h1>Hello Servlet " + helloService.getName() + "</h1>");
        resp.getWriter().println("</body>");
        resp.getWriter().println("</head>");
        resp.getWriter().println("</html>");
        resp.getWriter().println("</html>");
    }
    ...
}
----
<.> `ContextLoaderListener` 가 생성한 `ApplicationContext` 를 가져온다.
<.> `ApplicationContext` 에 등록된 빈을 가져온다.

=== HttpServlet을 상속받는 서블릿 컨트롤러 패턴의 단점
* URL 마다 서블릿을 생성하고 등록해야 한다. 반복 작업이 많고, 공통적인 부분에 대해 처리가 어려워지는 단점이 있다. 이것을 해결하기 위해 `FrontController` 패턴을 사용하는 스프링 MVC를 연동해보자. 스프링 MVC의 핵심은 `DispatcherServlet` 이다.

== Spring MVC 연동
하나의 어플리케이션 안에는 한 개 이상의 `DispatcherServlet` 을 등록할 수 있기 때문에,  `DispatcherServlet` 을 등록할 때, `WebApplicationContext` 가 있다면 `WebApplicationContext` 를 부모로 하는 `WebApplicationContext` 를 하나 더 만든다. 부모 `WebApplicationContext` 는 다른 `DispatcherServlet` 간에도 공유가 가능하다.

.web.xml
[,xml]
----
<servlet>
    <servlet-name>app</servlet-name>
    <servlet-class>org.springframework.web.servlet.DispatcherServlet</servlet-class>
    <init-param> <.>
      <param-name>contextClass</param-name>
      <param-value>org.springframework.web.context.support.AnnotationConfigWebApplicationContext</param-value>
    </init-param>
    <init-param>
      <param-name>contextConfigLocation</param-name>
      <param-value>hello.WebConfig</param-value>
    </init-param>
</servlet>
<servlet>
<servlet-mapping>
    <servlet-name>app</servlet-name>
    <url-pattern>/app/*</url-pattern>
</servlet-mapping>
----
<.> `DispatcherServlet` 이 `WebApplicationContext` 을 생성할 때 사용할 설정 파일 정보를 파라미터로 넘겨준다.

.AppConfig.java
[, java]
----
@Configurable
@ComponentScan(excludeFilters = @ComponentScan.Filter(Controller.class)) <.>
public class AppConfig {
}
----
<.> `ContextLoaderListener` 에서 생성하는 `WebApplicationContext` 에는 `Controller` 를 빈으로 등록하지 않는다.

.WebConfig.java
[, java]
----
@Configurable
@ComponentScan(useDefaultFilters = false, includeFilters = @ComponentScan.Filter(Controller.class)) <.>
public class WebConfig {
}
----
<.> `DispatcherServlet이` 에서 생성하는 `WebApplicationContext` 에는 `Controller` 를 빈으로 등록한다.

.HelloController.java
[, java]
----
@RestController <.>
public class HelloController {

    @Autowired
    HelloService helloService;

    @GetMapping("/hello2")
    public String hello() {
        return "hello, " + helloService.getName();
    }
}
----
<.> `DispatcherServlet` 이 생성하는 `WebApplicationContext` 에 `HelloController` 가 빈으로 등록되며, `DispatcherServlet` 은 `/app/*` 으로 들어오는 요청들을 해당하는 컨트롤러로 `dispatch` 해줄 수 있다.