= 함수형 인터페이스와 람다
:listing-caption!:

== 람다
람다는 자바 1.8 부터 지원되는 기능이다. 람다의 도입으로 인해 자바는 객체지향 언어인 동시에 함수형 프로그래밍도 가능한 언어가 되었다. 자바에서의 함수는 매개변수로 전달할 수 있고 반환 타입에도 사용 가능한 일급 객체로 취급되는데, 람다의 타입으로 사용하기 위한 함수형 인터페이스도 도입되었다. 메서드를 재정의하여 원하는 동작을 구현하기 위한 방법으로 자주 사용했었던 템플릿 메서드 패턴 외에도, 함수 객체를 매개 변수로 받는 메소드를 사용하여 구현할 수 있게 되었다. 컬렉션 인터페이스들에도 함수형 인터페이스와 람다를 사용한 다양한 디폴트 메서드가 추가되기도 했다.

=== 람다식
람다식은 메서드를 하나의 식(expression)으로 표현한 것으로, 함수형 인터페이스를 인라인으로 구현한 특수한 형태의 객체이다. 이름 없는 함수이기 때문에 `익명 함수` 라고도 한다.

.Example1
[,java]
----
int max(int a, int b) {
    return a > b ? a : b;
}
----
위와 같은 메서드를 람다식으로 변환하면 다음과 같다.
[, java]
----
(int a, int b) -> { return a > b ? a : b }; <.>
(int a, int b) -> a > b ? a : b <.>
(a, b) -> a > b ? a : b <.>
----
<.> 반환 타입 및 매서드 이름을 삭제하고, 중간에 `->` 를 추가한다.
<.> 간단한 한 줄의 반환 타입으로 이루어질 경우, `중괄호({})` 와 `return`, `세미콜론(;)` 을 삭제할 수 있다.
<.> 타입 추론이 가능한 대부분 경우 매개변수의 타입도 삭제할 수 있다. (전부 삭제하거나 전부 넣거나 해야 한다.)

.Example2
[,java]
----
int value(int a) {
    return a;
}
----
위 처럼 매개 변수가 하나인 경우 타입을 생략한다면 `괄호(())` 도 삭제 가능하다.
[,java]
----
(int a) -> a <.>
a -> a
----
<.> 타입이 있을 경우 괄호도 있어야 한다.

.Example3
[,java]
----
void value() {
    System.out.println("람다식을 공부해봐요.");
}
----
위 처럼 매개변수가 없을 경우에는 `()` 로 표현해야 한다.

[,java]
----
() -> System.out.println("람다식을 공부해봐요.")
----


== 함수형 인터페이스
람다식을 어떻게 만드는지는 알아봤는데, 그렇다면 위 람다식을 호출하기 위해서는 어떻게 할까? 일반 메소드의 경우 해당 메소드 이름으로 호출하게 되지만 람다식은 이름이 없다. 자바에서는 함수도 객체라고 했다. 람다식의 타입은 어떻게 될까?
[,java]
----
타입 f = (a, b) -> a > b ? a : b
----
* 자바에서는 람다식의 타입으로 `함수형 인터페이스` 를 사용하도록 한다.
** 람다식의 매개변수의 타입과 개수, 반환값이 일치하는 인터페이스 메소드가 있다면 해당 람다식의 타입으로 사용할 수 있다.
** 함수형 인터페이스는 `static` 메소드와 `default` 메소드를 제외하고 단 하나의 메소드만 정의되어 있어야 한다.
* 엄밀히 말하면 람다식은 익명 객체이고 타입이 존재하지 않는데, 함수형 인터페이스의 타입으로 형변환이 가능하며, 이를 생략한 것이다.
[,java]
----
@FunctionalInterface
interface FunctionalInterface {
    int max(int a, int b);
}
----
이는 인터페이스나 클래스를 익명 클래스를 사용해서 구현하는 것과도 같은 흐름이다.
[,java]
----
FuntionalInterface 익명내부클래스 = new FuntionalInterface() {
    @Override
    public int max(int a, int b) {
        return a > b ? a : b;
    }
};

FuntionalInterface 람다 = (a, b) -> a > b ? a : b;
----

위에서 보면 인터페이스에 `@FunctionalInterface` 어노테이션을 사용했다.

* 해당 인터페이스가 람다용으로 설계된 함수형 인터페이스임을 알려준다.
* 이 어노테이션이 붙어있을 경우, 추상 메서드를 하나만 가질 수 있도록 컴파일 시에 체크해준다.

=== 표준 함수형 인터페이스
`https://docs.oracle.com/javase/8/docs/api/java/util/function/package-summary.html[java.util.function]` 패키지에는 일반적으로 자주 쓰이는 형식의 메소드를 함수형 인터페이스로 미리 정의해놓았다. 대부분은 직접 구현하지 않고도 표준 함수형 인터페이스를 사용할 수 있을 것이고, 유용한 디폴트 메소드들도 많이 제공하기 때문에 미리 알아놓으면 좋다.

[%autowidth, cols="^,^,"]
|===
|인터페이스 |함수 시그니처 |설명

|Function<T, R> |R apply(T t) |T 타입을 받아서 R 타입을 리턴
|BiFunction<T, U, R> |R apply(T t, U u)|매개변수로 T, U 두 개의 타입을 받아서 R 타입을 반환
|Supplier<T> |T get() |인자는 없고 T 타입을 반환
|Consumer<T> |void accept(T t) |T 타입을 받고 반환값은 없음
|Predicate<T> |boolean test(T t) |T 타입을 받고 boolean 타입을 반환

|===

.Function<T, R>
[#Function,java]
----
@FunctionalInterface
public interface Function<T, R> {
    R apply(T t);

    default <V> Function<V, R> compose(Function<? super V, ? extends T> before) {
        Objects.requireNonNull(before);
        return (V v) -> apply(before.apply(v));
    }

    default <V> Function<T, V> andThen(Function<? super R, ? extends V> after) {
        Objects.requireNonNull(after);
        return (T t) -> after.apply(apply(t));
    }
}
----
`Function<T, R>` 인터페이스를 사용해서 매개변수에 10을 더하거나, 2를 곱하는 람다식을 작성해보면 다음과 같다. 이 때, 매개변수와 반환값은 모두 `Integer` 이다.
[,java]
----
Function<Integer, Integer> plus10 = (i) -> i + 10;
Function<Integer, Integer> multiply2 = (i) -> i * 2;
----
위는 식을 정의한 것이고, 실제로 함수가 실행되기 위해서는 `apply()` 메소드를 호출해야 한다.
[,java]
----
plus10.apply(10); // 12
multiply2.apply(10); // 20
----

xref:Function[] 을 보면 `compose` 와 `andThen` 디폴트 함수를 볼 수 있는데 두 가지의 `Function` 람다식을 조합해서 새로운 람다식을 생성한다.

* `compose()` 는 매개변수로 또 다른 `Function<V, R>` 람다식을 받아서 `apply()` 를 먼저 실행한다. 그리고 여기서 반환된 값을 매개변수로 하여 `apply()` 를 실행한다.
+
[,java]
----
Function<Integer, Integer> compose = plus10.compose(multiply2);
// Function<Integer, Integer> compose = (v) -> plus10.apply(multiply2.apply(v)); <.>
compose.apply(5); // 60 <.>
----
<.> 결국 `compose()` 메소드에서 반환되는 람다식은 이렇다.
<.> 먼저 `multiply2` 의 `apply()` 가 실행되어 `50` 이 반환되고, `50` 은 `plus10` 의 매개변수로 들어가서 `apply()` 가 실행되어 `60` 이 반환된다.

* `andThen()` 는 먼저 현재 `this` 객체의 `apply()` 를 실행한다. 그리고 여기서 반환된 값을 매개변수로 하여 `andThen()` 메소드의 매개변수로 받았던 객체의 `apply()` 를 실행한다.
+
[,java]
----
Function<Integer, Integer> andThen = plus10.compose(multiply2);
// Function<Integer, Integer> andThen2 = (t) -> multiply.apply(plus10.apply(t)); <.>
andThen.apply(5); // 150 <.>
----
<.> 결국 `andThen()` 메소드에서 반환되는 람다식은 이렇다.
<.> 먼저 `apply` 의 `apply()` 가 실행되어 `15` 가 반환되고, `15` 은 `multiply2` 의 매개변수로 들어가서 `apply()` 가 실행되어 `150` 이 반환된다.

위에서 작성해본 예제는 `Integer` 를 매개변수로 받아서 같은 타입을 리턴한다. `java.util.function` 패키지에는 하나의 타입을 받아서 같은 타입을 리턴하는 `UnaryOperator<T>` 가 존재한다.
[%autowidth, cols="^,^,"]
|===
|인터페이스 |함수 시그니처 |설명
|UnaryOperator<T> |T apply(T t) | Function<T, T> 를 상속받은 인터페이스로 매개변수로 받은 타입과 반환 타입이 일치한다.
|BinaryOperator<T>|R apply(T t, U u)| BiFunction<T,T,T> 를 상속받은 인터페이스로 매개변수 2개와 반환 타입이 모두 일치한다.
|===

[,java]
----
UnaryOperator<Integer> plus10 = (i) -> i + 10;
plus10.apply(2); // 12
BinaryOperator<Integer> max = (a, b) -> a > b ? a : b;
max.apply(1, 3); // 3
----

지금까지는 제네릭 타입으로 함수형 인터페이스를 사용하기 위해서 박싱된 기본 타입을 사용했다. 자바는 기본형을 위한 함수형 인터페이스도 제공한다.
[%autowidth, cols="^,^,"]
|===
|인터페이스 |함수 시그니처 |설명
|IntFunction<R>|R apply(int value)|T 타입을 받아서 int 타입을 반환
|DoubleFunction<R>|R apply(double value)|T 타입을 받아서 double 타입을 반환
|LongFunction<R>|R apply(long value)|long 타입을 받아서 R 타입을 반환
|ToDoubleFunction<T>|double applyAsDouble(T value)|T 타입을 받아서 double 타입을 반환
|ToIntFunction<T>|int applyAsInt(T value)|T 타입을 받아서 int 타입을 반환
|ToLongFunction<T>|long applyAsLong(T value)|T 타입을 받아서 long 타입을 반환
|IntUnaryOperator|int applyAsInt(int operand)|int 타입을 받아서 int 타입을 반환
|===
[,java]
----
IntFunction<Integer> plus10 = (i) -> i + 10;
plus10.apply(2); // 12
IntUnaryOperator plus10_unary = (i) -> i + 10;
plus10_unary.applyAsInt(2) // 12
----

이 외에도 제일 위에서 살펴본 `Consumer`, `Predicate`, `Supplier` 인터페이스도 마찬가지로 기본형 인터페이스를 제공한다.


== 람다식과 메소드 참조
=== 람다식의 로컬 변수 사용
람다식은 익명 구현 객체, 로컬 클래스와 마찬 가지로 바깥 클래스의 모든 필드와 메소드에 접근 가능하다. 그리고 메소드 내에서 정의되었을 경우, 메소드 내에서 정의된 지역 변수도 사용 가능하다. 하지만 이 지역 변수들은 메소드의 실행이 끝나면 스택 메모리에서 사라진다. 정의한 람다식의 참조가 남아 있어 실행 가능할 경우 어떻게 될까?

[,java]
----
public class LambdaStudy {

    private String classVar = "[클래스 멤버 변수]";
    private Supplier<String> lambda;

    <1>
    public void createLambda(String argVar) {
        String localVar = "[로컬 변수]";
        lambda = () -> argVar + " " + localVar + " " + this.classVar;
    }

    public static void main(String[] args) {
        LambdaStudy lambdaStudy = new LambdaStudy();
        lambdaStudy.createLambda("[매개 변수]"); <2>

        System.out.println(lambdaStudy.lambda.get()); <3>
    }
}

----
<1> `lambda` 라는 람다식을 정의한다. 이 식 안에는 매개 변수인 `argVar` 와 로컬 변수인 `localVar` 가 사용되었다.
<2> `argVar` 에 값을 넘겨주면서 메소드를 호출한다. 그리고 메소드가 종료되면 내부의 지역 변수들은 사라진다.
<3> 실행 결과는 `[매개 변수] [로컬 변수] [클래스 멤버 변수]` 이다. 사라진 지역 변수들에 대한 값도 갖고 있다. 어떻게 된 걸까?

인텔리제이에서 지원하는 바이트코드 보기 기능으로 확인해보면 아래와 같은 부분을 볼 수 있다.
[,]
----
<1>
private synthetic lambda$createLambda$0(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
L0
LINENUMBER 12 L0
ALOAD 1
ALOAD 2
ALOAD 0
GETFIELD study/lambda/LambdaStudy.classVar : Ljava/lang/String;
INVOKEDYNAMIC makeConcatWithConstants(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String; [
  // handle kind 0x6 : INVOKESTATIC
  java/lang/invoke/StringConcatFactory.makeConcatWithConstants(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite;
  // arguments:
  "\u0001 \u0001 \u0001"
]
ARETURN
L1

LOCALVARIABLE this Lstudy/lambda/LambdaStudy; L0 L1 0
LOCALVARIABLE argVar Ljava/lang/String; L0 L1 1 <2>
LOCALVARIABLE localVar Ljava/lang/String; L0 L1 2
MAXSTACK = 3
MAXLOCALS = 3
}

----
<1> `synthetic` 은 자바 컴파일러에 의해 생성된 메소드를 가리킨다.
<2> 람다식에서 사용했던 메소드 내의 지역 변수들을 (또는 참조 값) 그대로 복사해온다는 걸 알 수 있다.

익명 구현 객체와 로컬 클래스도 마찬 가지이다. 그렇다면, 람다식에서 해당 지역 변수를 복사해간 이후에 메소드에서 해당 값을 바꿔 버리면 어떻게 될까? 자바는 이것을 막기 위해 `final` 로 선언된 변수만 사용 가능 하도록 하여 변수를 초기화한 이후에는 값을 변경할 수 없도록 했다. 자바 8 부터는 `final` 변수가 아니라도, 변수를 초기화한 이후에 값이 변경되지 않는 다면 `사실상 final` 변수로 판단하여 사용 가능하다.

[,java]
----
public void createLambda(String argVar) {
    String localVar = "[로컬 변수]";
    lambda = () -> argVar + " " + localVar + " " + this.classVar; <1>

    localVar = "값을 변경하고 싶습니다";
}
----
<1> `localVar` 값을 초기화한 후에 변경하려고 할 경우 (위치와 상관 없이) 에러가 발생 한다.
* `Variable used in lambda expression should be final or effectively final`
* `final` 과는 달리 선언과 동시에 값을 초기화하지 않더라도 컴파일 에러는 발생하지 않는다.
* 람다 내부에서도 사용되는 변수 임을 명시적으로 표시하기 위해 `final` 을 사용하는게 좋을 것 같아 보인다.

=== 람다식의 스코프

[,java]
----
public class WhatIsThis {
    public void createLambda() {
        String name = "JAVA";
        Supplier<String> lambda = () -> {
            String name = "Stranger"; <.>
            return "Hello, " + name;
        };
    }
}
----
<.> 컴파일 에러가 발생한다.
* `Variable 'name' is already defined in the scope`

새로운 스코프를 생성하는 익명 클래스나 로컬 클래스와는 다르게, 람다식은 람다식을 정의한 메소드와 동일한 스코프기 때문에 같은 이름의 변수를 선언할 수 없다. 익명 클래스나 로컬 클래스 내부에서 `this` 를 사용하면 익명 클래스의 객체, 로컬 클래스의 객체 참조를 가리키지만, 람다식에서의 `this` 는 람다식을 실행하는 객체의 참조를 가진다.

=== 메소드 참조
람다가 하는 일이 기존 메소드 또는 생성자 같은 단 하나의 메소드만 호출하는 경우에는 메소드 레퍼런스를 사용해서 매우 간결하게 표현할 수 있다.

* 메소드 또는 생성자의 매개변수로 람다의 입력값을 받는다.
* 리턴값 또는 생성한 객체는 람다의 리턴값이다.


[%autowidth, cols="^,^,^"]
|===
|종류 |람다 |메소드 참조
|정적 메소드 참조 |(x) -> ClassName.method(x) |ClassName::method
|특정 인스턴스 메소드 참조 |(x) -> object.method(x) |object::method
|인스턴스 메소드 참조 |(object, x) -> object.method(x) |ClassName::method
|생성자 메소드 참조 |() -> new ClassName()|ClassName::new
|===

==== 정적 메소드 참조
두 개의 `int` 를 매개 변수로 받아서 더한 뒤 결과 `int` 를 리턴하는 람다식을 만들고 싶을 때 사용할 수 있는 함수형 인터페이스는 `BinaryOperator` 이다.

.lambda
[#lambda1,java]
----
IntBinaryOperator sum = (a, b) -> a + b;
----
자바 8부터 `Interger` 클래스에서는 `sum` 이라는 정적 함수를 제공하는데, 우리가 위에서 구현한 것과 동일한 동작이다.

.Integer.java
[,java]
----
public final class Integer extends Number implements Comparable<Integer> {
    /**
     * Adds two integers together as per the + operator.
     *
     * @param a the first operand
     * @param b the second operand
     * @return the sum of {@code a} and {@code b}
     * @see java.util.function.BinaryOperator
     * @since 1.8
     */
    public static int sum(int a, int b) { <.>
        return a + b;
    }
}
----
위 함수를 사용하도록 람다식을 바꿔보자.
[,java]
----
IntBinaryOperator sum = (a, b) -> Integer.sum(a, b);
----
위 람다식은 단순히 메소드 하나만 호출하는 것이기 때문에 다음과 같이 메소드 참조로 변경할 수 있다.
[,java]
----
IntBinaryOperator sum = Integer::sum;
----

==== 특정 인스턴스의 메소드 참조
객체를 생성해서 메소드 하나를 호출하는 람다식을 만들어보자.
[,java]
----
class Foo {
    public String getName() {
        return "Stranger";
    }
}
public void studyingMethodRef() {
    Foo foo = new Foo();
    Supplier<String> supplier = () -> foo.getName();
}
----
위 람다식은 다음과 같이 메소드 참조로 변경할 수 있다.

[,java]
----
public void studyingMethodRef() {
    Foo foo = new Foo();
    Supplier<String> supplier = foo::getName;
}
----

==== 임의 인스턴스의 메소드 참조
`Arrays` 클래스에는 정렬 메소드가 있는데, 아래는 알파벳 순으로 정렬된다. 이 때 대문자가 소문자보다 우선 순위가 높다.
[,java]
----
String[] names = {"Jake", "Amy", "Holt", "boyle", "gina"};
Arrays.sort(names); // Amy, Holt, Jake, boyle, gina
----

`Arrays` 클래스에는 `Comparator` 라는 함수형 인터페이스를 파라미터로 받는 정렬 메소드도 있다.

.Arrays.java
[,java]
----
public static <T> void sort(T[] a, Comparator<? super T> c) {
    if (c == null) {
        sort(a);
    } else {
        if (LegacyMergeSort.userRequested)
            legacyMergeSort(a, c);
        else
            TimSort.sort(a, 0, a.length, c, null, 0, 0);
    }
}
----
.Comparator.java
[,java]
----
@FunctionalInterface
public interface Comparator<T> {
    int compare(T o1, T o2);
}
----

대소문자에 상관없이 정렬하고 싶다면 `String` 클래스의 `compareToIgnoreCase()` 를 사용할 수 있다.

[,java]
----
public int compareToIgnoreCase(String str) {
    return CASE_INSENSITIVE_ORDER.compare(this, str);
}
----

[,java]
----
String[] names = {"Jake", "Amy", "Holt", "boyle", "gina"};
Arrays.sort(names, (o1, o2) -> o1.compareToIgnoreCase(o2)); <.>
----
<.> 처음 공부할 때 여길 이해하는게 뭔가 어려웠는데, 풀어서 생각해보면 쉽다. `Arrays.sort` 메소드는 정렬 과정에서 아래 같은 식으로 `comparator.compare()` 메소드를 호출하게 될텐데, 앞의 `o1` 은 `String` 의 `this` 객체가 되는 것이고, `o2` 는 `compareToIgnoreCase()` 메소드의 파라미터로 넘겨지게 되는 것이다.
+
[,java]
----
Comparator<String> comparator = (o1, o2) -> o1.compareToIgnoreCase(o2);
int result = comparator.compare("Jake", "Amy");
----

위의 람다식은 아래처럼 메소드 참조로 변경할 수 있다.
[,java]
----
String[] names = {"Jake", "Amy", "Holt", "boyle", "gina"};
Arrays.sort(names, String::compareToIgnoreCase);
----

보면 임의 인스턴스의 메소드 참조와 정적 메소드 참조는 형태가 동일하지만, 실제 메소드가 `static` 인지 아닌지로 구분할 수 있다.

==== 생성자 메소드 참조
람다식에서 단순히 객체를 생성하기만 한다면 생성자 메소드 참조로 변경할 수 있다.
[,java]
----
Supplier<Foo> supplier = () -> new Foo();
Foo foo = supplier.get();
----
[,java]
----
Supplier<Foo> supplier = Foo::new;
Foo foo = supplier.get();
----
위에서는 기본 생성자를 사용했기 때문에 매개 변수는 없고, 반환 타입은 `Foo` 타입인 `Supplier<Foo>` 인터페이스를 사용했다. 매개 변수가 있는 생성자를 호출할 때는 어떻게 될까?
[,java]
----
// Foo foo = new Foo("hello");
Function<String, Foo> function = str -> new Foo(str);
Foo foo = function.apply("hello");
----
[,java]
----
// Foo foo = new Foo("hello");
Function<String, Foo> function = Foo::new;
Foo foo = function.apply("hello");
----
생성자가 오버로딩 되었을 때, 생성자 참조만 놓고보면 형태가 동일하기 때문에 어떤 것을 호출하게 될지 알 수 없다. 컴파일 시에 매칭되는 생성자가 존재하지 않으면 에러가 발생한다.

== 참고 및 출처
* https://blog.frankel.ch/synthetic/[Synthetic]
* https://www.inflearn.com/course/the-java-java8/dashboard[인프런 - 더 자바, Java 8]
* https://product.kyobobook.co.kr/detail/S000061695652[도서 - 이것이 자바다]
* https://product.kyobobook.co.kr/detail/S000001550352[도서 - 자바의 정석]